replicaCount: 1

image:
  repository: ghcr.io/beep-industries/media-server
  tag: ""
  pullPolicy: IfNotPresent

service:
  grpcPort: 50051
  mediaPort: 3478

env:
  SFU_HOST: "0.0.0.0"
  SFU_PORT: "8080"
  MEDIA_PORT: "3478"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

stunner:
  enabled: true
  udpGateway: udp-gateway
  udpRouteNamespace: stunner
  grpcGateway: web
  grpcGatewayNamespace: gateway
  hostname: beep.ovh
