apiVersion: v1
kind: Service
metadata:
  name: sfu-server
  namespace: sfu
spec:
  selector:
    app: sfu-server
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      appProtocol: kubernetes.io/grpc
    - name: media
      port: 3478
      targetPort: 3478
      protocol: UDP

